# build.ps1
#
# Optional dev-only helper — Windows/PowerShell equivalent of build.js.
# Bundles data/content.json into data/bundle.js so the app can be opened
# directly via file:// (browsers block fetch() of local JSON files under
# file://, but a plain <script> tag always works).
#
# data/content.json remains the source of truth — re-run this after
# editing or adding phrases/templates:
#
#   powershell -ExecutionPolicy Bypass -File build.ps1
#
# Requires no installs (uses only built-in PowerShell cmdlets). Never
# required to USE the finished app, only to regenerate the bundle after
# editing content.json. Prefer build.js (node build.js) if you have Node
# installed; this does the same thing without it.

$ErrorActionPreference = 'Stop'
$dataDir = Join-Path $PSScriptRoot 'data'

$raw = (Get-Content (Join-Path $dataDir 'content.json') -Raw).Trim()
$parsed = $raw | ConvertFrom-Json  # validate before trusting the raw text splice

$banner = "// AUTO-GENERATED by build.ps1 -- do not edit by hand.`n// Source of truth is data/content.json.`n// Re-run (powershell -ExecutionPolicy Bypass -File build.ps1) after changing content.json.`n"
$contents = $banner + "window.WARDOGS_DATA = $raw;`n"

Set-Content -Path (Join-Path $dataDir 'bundle.js') -Value $contents -Encoding utf8 -NoNewline

Write-Output "Bundled $($parsed.templates.Count) templates and $($parsed.phrases.Count) phrases into data/bundle.js"
