# build.ps1
#
# Optional dev-only helper — Windows/PowerShell equivalent of build.js.
# Bundles data/announcements.txt into data/bundle.js so the app can be
# opened directly via file:// (browsers block fetch() of local files
# under file://, but a plain <script> tag always works).
#
# data/announcements.txt remains the source of truth — re-run this after
# editing it:
#
#   powershell -ExecutionPolicy Bypass -File build.ps1
#
# Requires no installs (uses only built-in PowerShell). Never required to
# USE the finished app, only to regenerate the bundle after editing the
# list. Builds the JSON array manually (instead of ConvertTo-Json) to
# sidestep PowerShell 5.1's single-element-array collapsing quirk.

$ErrorActionPreference = 'Stop'
$dataDir = Join-Path $PSScriptRoot 'data'
$sourceFile = Join-Path $dataDir 'announcements.txt'
$outputFile = Join-Path $dataDir 'bundle.js'

function ConvertTo-JsStringLiteral([string]$s) {
    $s = $s -replace '\\', '\\\\'
    $s = $s -replace '"', '\"'
    $s = $s -replace "`r", ''
    $s = $s -replace "`t", '\t'
    $s = $s -replace "`n", '\n'
    return '"' + $s + '"'
}

$rawLines = Get-Content -Path $sourceFile -Encoding utf8
$lines = @()
foreach ($line in $rawLines) {
    $trimmed = $line.Trim()
    if ($trimmed.Length -gt 0) { $lines += $trimmed }
}

$jsonItems = $lines | ForEach-Object { ConvertTo-JsStringLiteral $_ }
$jsonArray = "[`n  " + ($jsonItems -join ",`n  ") + "`n]"

$banner = "// AUTO-GENERATED by build.ps1 -- do not edit by hand.`n// Source of truth is data/announcements.txt.`n// Re-run (powershell -ExecutionPolicy Bypass -File build.ps1) after changing that file.`n"
$contents = $banner + "window.WARDOGS_LINES = $jsonArray;`n"

Set-Content -Path $outputFile -Value $contents -Encoding utf8 -NoNewline

Write-Output "Bundled $($lines.Count) announcement(s) into data/bundle.js"
