#!/usr/bin/env node
/**
 * build.js
 *
 * Optional dev-only helper. Bundles data/content.json into data/bundle.js
 * so the app can be opened directly via file:// (browsers block fetch()
 * of local JSON files under file://, but a plain <script> tag always
 * works).
 *
 * data/content.json remains the source of truth — re-run this after
 * editing or adding phrases/templates:
 *
 *   node build.js
 *
 * Requires only Node's built-in `fs`/`path` — no npm install, no
 * dependencies. This script is never required to USE the finished app,
 * only to regenerate the bundle after editing content.json.
 */
const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, 'data');
const CONTENT_FILE = 'content.json';
const OUTPUT_FILE = path.join(DATA_DIR, 'bundle.js');

function build() {
  const raw = fs.readFileSync(path.join(DATA_DIR, CONTENT_FILE), 'utf8');
  let content;
  try {
    content = JSON.parse(raw);
  } catch (e) {
    throw new Error(`Failed to parse ${CONTENT_FILE}: ${e.message}`);
  }

  const banner =
    '// AUTO-GENERATED by build.js — do not edit by hand.\n' +
    '// Source of truth is data/content.json.\n' +
    '// Re-run `node build.js` after changing content.json.\n';
  const contents = `${banner}window.WARDOGS_DATA = ${JSON.stringify(content, null, 2)};\n`;

  fs.writeFileSync(OUTPUT_FILE, contents, 'utf8');
  console.log(
    `Bundled ${content.templates.length} templates and ${content.phrases.length} phrases into data/bundle.js`
  );
}

build();
