#!/usr/bin/env node
/**
 * build.js
 *
 * Optional dev-only helper. Bundles data/announcements.txt into
 * data/bundle.js so the app can be opened directly via file:// (browsers
 * block fetch() of local files under file://, but a plain <script> tag
 * always works).
 *
 * data/announcements.txt remains the source of truth — re-run this after
 * editing it:
 *
 *   node build.js
 *
 * Requires only Node's built-in `fs`/`path` — no npm install, no
 * dependencies. Never required to USE the finished app, only to
 * regenerate the bundle after editing the list.
 */
const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, 'data');
const SOURCE_FILE = 'announcements.txt';
const OUTPUT_FILE = path.join(DATA_DIR, 'bundle.js');

function build() {
  const raw = fs.readFileSync(path.join(DATA_DIR, SOURCE_FILE), 'utf8');
  const lines = raw
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);

  const banner =
    '// AUTO-GENERATED by build.js — do not edit by hand.\n' +
    '// Source of truth is data/announcements.txt.\n' +
    '// Re-run `node build.js` after changing that file.\n';
  const contents = `${banner}window.WARDOGS_LINES = ${JSON.stringify(lines, null, 2)};\n`;

  fs.writeFileSync(OUTPUT_FILE, contents, 'utf8');
  console.log(`Bundled ${lines.length} announcement(s) into data/bundle.js`);
}

build();
